name: Build and test Raivo for iOS

on:
  push:
    branches: [ master, testflight, develop ]
  pull_request:
    branches: [ master, testflight, develop ]

jobs:
  build:
    name: Build and test the debug scheme using various iPhone simulators
    runs-on: macos-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - destination: 'name=iPhone 12 Pro,OS=14.5'
            scheme: 'Raivo DEBUG'
          - destination: 'name=iPhone 13 Pro,OS=15.0'
            scheme: 'Raivo DEBUG'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.4'
      - name: Prepare custom devices
        run: |
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
      - name: Prepare iOS 14.5 simulator
        if: contains(matrix.destination, 'OS=14.5')
        run: |
          xcversion simulators --install='iOS 14.5'
          xcrun simctl create iPhone-12-Pro "iPhone 12 Pro" "com.apple.CoreSimulator.SimRuntime.iOS-14-5"
          xcrun simctl list devices 14.5
      - name: Prepare iOS 15.0 simulator
        if: contains(matrix.destination, 'OS=15.0')
        run: |
          xcversion simulators --install='iOS 15.0'
          xcrun simctl create iPhone-13-Pro "iPhone 13 Pro" "com.apple.CoreSimulator.SimRuntime.iOS-15-0"
          xcrun simctl list devices 15.0
      - name: Build and test
        run: |
          xcodebuild build test -project ${project} -scheme "${scheme}" -destination "${destination}" | xcpretty && exit ${PIPESTATUS[0]}
        env:
          project: 'Raivo.xcodeproj'
          scheme: ${{ matrix.scheme }}
          destination: ${{ matrix.destination }}
